stages:
  - test
  - coverage
  - pages

variables:
  CRAW_HOME: ${CI_PROJECT_DIR}
  CRAW_VERSION: ${CI_COMMIT_REF_NAME}

testing:
  stage: test
  image: registry-gitlab.pasteur.fr/bneron/macsyfinder:run_dep
  script:
    - python ${CI_PROJECT_DIR}/tests.py -vvv
  except:
    - /^feat.*$/
    - /^fix.*$/

coverage:
  stage: coverage
  image: registry-gitlab.pasteur.fr/gem/macsyfinder:coverage
  script:
    - cd ${CI_PROJECT_DIR}
    - coverage run --source=craw tests.py --unit
    - coverage html
    - coverage report
  artifacts:
    paths:
      - htmlcov/
  except:
    - /^feat.*$/
    - /^fix.*$/

pages:
  stage: pages
  image: registry-gitlab.pasteur.fr/gem/macsyfinder:pages
  dependencies:
    - coverage
  script:
    - cd ${CI_PROJECT_DIR}/doc/
    - make html
    - cd ${CI_PROJECT_DIR}
    - mv ${CI_PROJECT_DIR}/doc/build/html/ public
    - mv htmlcov public/
  artifacts:
    paths:
      - public
  only:
    - master

