language: python
python:
  - "2.7"
# Apply only on main branches
branches:
  except:
       - /^feature.*$/
       
# command to install Ubuntu dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install hmmer
  - sudo apt-get install ncbi-blast+

# command to install python dependencies
install: 
- "pip install coverage"
- "pip install python-coveralls"

# command to run tests
script:
- python setup.py build
- python setup.py install
- python tests.py -vv
- /home/travis/virtualenv/python2.7.9/bin/macsyfinder --def=/home/travis/build/gem-pasteur/macsyfinder/tests/data/data_set_1/def --profile-dir=/home/travis/build/gem-pasteur/macsyfinder/tests/data/data_set_1/profiles --out-dir=/tmp/macsyfinder_test_basic_run --sequence-db=/home/travis/build/gem-pasteur/macsyfinder/tests/data/base/test_aesu.fa --db-type=gembase T9SS T3SS T4SS_typeI
- cat /tmp/macsyfinder_test_basic_run/hmmer_results/T9SS_porQ.search_hmm.err
- ls -l /tmp/macsyfinder_test_basic_run
- python -m json.tool /tmp/macsyfinder_test_basic_run/results.macsyfinder.json

after_success:
  - coveralls
