language: python
python:
  - "2.7"
# Apply only on main branches
branches:
  except:
       - /^feature.*$/
       
# command to install Ubuntu dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install hmmer
  - sudo apt-get instal ncbi-blast+

       
# command to install python dependencies
install: 
- "pip install coverage"
- "pip install python-coveralls"
# command to run tests
script:
- python setup.py build
- python setup.py test -vv
- cd test && coverage run --source ../macsypy main.py && coverage html
after_success:
  - coveralls
