language: python
python:
  - "2.7"
# Apply only on main branches
branches:
  except:
       - /^feature.*$/
# command to install dependencies
install: 
- "pip install coverage"
- "pip install python-coveralls"
- "pip install -r requirements.txt --use-mirrors"
# command to run tests
script:
- python setup.py build
- python setup.py test -vv
- cd test && coverage run --source ../macsypy main.py && coverage html
after_success:
  - coveralls
